apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      app: php-apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
        - image: asia.gcr.io/devops-rnd-328408/php-apache:latest
          name: php-apache
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "500Mi"
          ports:
            - containerPort: 80
              name: http